algorithm: 'carefl'

data:
  video_idx: 0
  image_size: 500
  crop_size: 224
  lag: [1, 2, 3]
  pca: false
  n_components: 100


flow:
  architecture: 'CL'
  net_class: 'MLP'  # in {'MLP', 'ARMLP', 'MLP4', 'CONV}.lower()
  nl: 3
  nh: 50
  batch_norm: false
  prior_dist: 'laplace'
  # for CL
  scale_base: true
  shift_base: true

training:
  epochs: 500
  verbose: false
  split: .8
  seed: 0
  batch_size: 64


optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false
  scheduler: true


